---

common_enabled:  true
desktop_enabled: true
network_enabled: true
gaming_enabled:  true
developement_enabled : true


filezilla_enabled:            true
firefox_enabled:              true
gimp_enabled:                 true
indicator_sysmonitor_enabled: true
java_openjdk_enabled:         true
libreoffice_enabled:          true
python_enabled:               true
snapd_enabled:                true
ssh_enabled:                  true
ufw_enabled:                  true
vagrant_enabled:              true
virtualbox_enabled:           true
nmap_enabled:                 true
qemu_enabled:                 true
virt_manager_enabled:         true
cutecom_enabled:              true
numix_circle_enabled:         true
neofetch_enabled:             true
steam_enabled:                true
lutris_enabled:               true
ipmitool_enabled:             true
gufw_enabled:                 true
wireshark_enabled:            true
discord_enabled:              true
openvpn_enabled:              true
visual_studio_code:           true
icedtea_netx_enabled:         true
terraform_enabled:            true
flameshot_enabled:            true

# http://docs.ansible.com/ansible/playbooks_variables.html#variable-precedence-where-should-i-put-a-variable
aptcachetime: 3600
timezone: "New York, United States"
ssh:
  start: true
  service_enabled: true
  password_auth: true
  root_login: true
