---

- name: Pop!_OS desktop environment playbook
  hosts: localhost
#  pre_tasks:
#    - name: Gathering Package Facts
#      package_facts:
#        manager: auto
#      tags:
#        - dbeaver
  roles:
    ## Common roles
    - role: common
      become: true
      tags:
        - common
      when: common_enabled | bool
    - role: ufw
      become: true
      tags:
        - ufw
        - system
        - common
      when: ufw_enabled | bool
    - role: snapd
      become: true
      tags:
        - snapd
        - system
        - common
      when: snapd_enabled | bool
    - role: docker
      become: true
      tags:
        - docker
        - development
        - development:infrastructure
        - desktop
      when: docker_enabled | bool
    - role: java-openjdk
      become: true
      tags:
        - java-openjdk
        - development
        - development:programing
        - developer
      when: java_openjdk_enabled | bool
    - role: ssh
      become: true
      tags:
        - ssh
        - network
        - developer
      when: ssh_enabled | bool
    - role: visual_studio_code
      become: true
      tags:
        - visual_studio_code
        - development
        - developer
      when: visual_studio_code | bool
    ## Desktop roles
    - role: desktop
      tags:
        - desktop
      when: desktop_enabled | bool
    - role: filezilla
      become: true
      tags:
        - filezilla
        - network
        - desktop
      when: filezilla_enabled | bool
    - role: firefox
      become: true
      tags:
        - firefox
        - network
        - desktop
      when: firefox_enabled | bool
    - role: gimp
      become: true
      tags:
        - gimp
        - graphics
        - desktop
      when: gimp_enabled | bool
    - role: libreoffice
      become: true
      tags:
        - libreoffice
        - office
        - desktop
      when: libreoffice_enabled | bool
    - role: remmina
      become: true
      tags:
        - remmina
        - network
        - desktop
      when: remmina_enabled | bool
    - role: vagrant
      become: true
      tags:
        - vagrant
        - development
        - development:infrastructure
      when: vagrant_enabled | bool
    - role: virtualbox
      become: true
      tags:
        - virtualbox
        - development
        - development:infrastructure
      when: virtualbox_enabled | bool
    - role: nmap
      become: true
      tags:
        - nmap
        - network
        - desktop
      when: nmap_enabled | bool
    - role: qemu
      become: true
      tags:
        - qemu
        - desktop
      when: qemu_enabled | bool
    - role: virt_manager
      become: true
      tags:
        - virt_manager
        - desktop
      when: virt_manager_enabled | bool
    - role: cutecom
      become: true
      tags:
        - cutecom
        - network
        - desktop
      when: cutecom_enabled | bool
    - role: numix_circle
      become: true
      tags:
        - numix_circle
        - desktop
      when: numix_circle_enabled | bool
    - role: neofetch
      become: true
      tags:
        - neofetch
        - desktop
      when: neofetch_enabled | bool
    - role: steam
      become: true
      tags:
        - steam
        - gaming
        - desktop
      when: steam_enabled | bool
    - role: lutris
      become: true
      tags:
        - lutris
        - gaming
        - desktop
      when: lutris_enabled | bool
    - role: ipmitool
      become: true
      tags:
        - ipmitool
        - network
        - desktop
      when: ipmitool_enabled | bool
    - role: gufw
      become: true
      tags:
        - gufw
        - network
        - desktop
      when: gufw_enabled | bool
    - role: gns3
      become: true
      tags:
        - gns3
        - network
        - desktop
      when: gns3_enabled | bool
    - role: wireshark
      become: true
      tags:
        - wireshark
        - network
        - desktop
      when: wireshark_enabled | bool
    - role: discord
      become: true
      tags:
        - discord
        - gaming
        - desktop
      when: discord_enabled | bool
    - role: openvpn
      become: true
      tags:
        - openvpn
        - network
        - desktop
      when: openvpn_enabled | bool
    - role: icedtea_netx
      become: true
      tags:
        - icedtea_netx
        - network
        - desktop
      when: icedtea_netx_enabled | bool
    - role: signal
      become: true
      tags:
        - signal
        - desktop
      when: signal_enabled | bool
    - role: gnome-screenshot
      become: true
      tags:
        - gnome-screenshot
        - desktop
      when: gnome-screenshot_enabled | bool
    - role: terraform
      become: true
      tags:
        - terraform
        - developer
      when: terraform_enabled | bool
