---

- name: Pop!_OS desktop environment playbook
  hosts: localhost
#  pre_tasks:
#    - name: Gathering Package Facts
#      package_facts:
#        manager: auto
#      tags:
#        - dbeaver
  roles:
    ## Common roles
    - role: locales
      become: true
      tags:
        - locale
        - common
      when: locales_enabled | bool
    - role: common
      become: true
      tags:
        - common
      when: common_enabled | bool
    - role: ufw
      become: true
      tags:
        - ufw
        - system
        - common
      when: ufw_enabled | bool
    - role: snapd
      become: true
      tags:
        - snapd
        - system
        - common
      when: snapd_enabled | bool
    - role: docker
      become: true
      tags:
        - docker
        - development
        - development:infrastructure
        - desktop
      when: docker_enabled | bool
    - role: java-openjdk
      become: true
      tags:
        - java-openjdk
        - development
        - development:programing
        - developer
      when: java_openjdk_enabled | bool
    #- role: ssh
    #  become: true
    #  tags:
    #    - ssh
    #    - network
    #    - developer
    #  when: ssh_enabled | bool
    ## Desktop roles
    - role: desktop
      tags:
        - desktop
      when: desktop_enabled | bool
    - role: 'pop_os/shell'
      tags:
        - pop_os
        - pop_os:shell
        - desktop
      when: pop_os_enabled or pop_os_shell_enabled | bool
    #- role: filezilla
    #  become: true
    #  tags:
    #    - filezilla
    #    - network
    #    - desktop
    #  when: filezilla_enabled | bool
    #- role: firefox
    #  become: true
    #  tags:
    #    - firefox
    #    - network
    #    - desktop
    #  when: firefox_enabled | bool
    - role: gimp
      become: true
      tags:
        - gimp
        - graphics
        - desktop
      when: gimp_enabled | bool
    - role: libreoffice
      become: true
      tags:
        - libreoffice
        - office
        - desktop
      when: libreoffice_enabled | bool
    - role: remmina
      become: true
      tags:
        - remmina
        - network
        - desktop
      when: remmina_enabled | bool
    - role: tmux
      become: true
      tags:
        - tmux
        - utility
        - desktop
      when: tmux_enabled | bool
    #- role: vagrant
    #  become: true
    #  tags:
    #    - vagrant
    #    - development
    #    - development:infrastructure
    #  when: vagrant_enabled | bool
    - role: virtualbox
      become: true
      tags:
        - virtualbox
        - development
        - development:infrastructure
      when: virtualbox_enabled | bool
    - role: nmap
      become: true
      tags:
        - nmap
        - network
        - desktop
      when: nmap_enabled | bool
    - role: qemu
      become: true
      tags:
        - qemu
        - network
        - desktop
      when: qemu_enabled | bool
    - role: virt_manager
      become: true
      tags:
        - virt_manager
        - network
        - desktop
      when: virt_manager_enabled | bool
    - role: cutecom
      become: true
      tags:
        - cutecom
        - network
        - desktop
      when: cutecom_enabled | bool
    - role: numix_circle
      become: true
      tags:
        - numix_circle
        - network
        - desktop
      when: numix_circle_enabled | bool
    - role: neofetch
      become: true
      tags:
        - neofetch
        - network
        - desktop
      when: neofetch_enabled | bool
    - role: steam
      become: true
      tags:
        - steam
        - network
        - desktop
      when: steam_enabled | bool
    - role: lutris
      become: true
      tags:
        - lutris
        - network
        - desktop
      when: lutris_enabled | bool
    - role: ipmitools
      become: true
      tags:
        - ipmitools
        - network
        - desktop
      when: ipmitools_enabled | bool    