---

- name: Add HashiCorp GPG key
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present
#Hardcoded the Ubuntu release version, not ideal
- name: Add HashiCorp apt repository
  apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    state: present
    filename: hashicorp
    update_cache: yes

- name: Install Terraform
  apt: 
    pkg: terraform
    state: present