---

- name: Download Ásbrú from Cloudsmith
  ansible.builtin.get_url: 
    url: https://dl.cloudsmith.io/public/asbru-cm/release/cfg/setup/bash.deb.sh
    dest: /tmp/asbru-cm-release_deb.sh
    owner: root
    group: root
    mode: "0755"  

- name: Execute the Ásbrú install script
  shell: /tmp/asbru-cm-release_deb.sh

- name: Install Ásbrú
  apt: 
    name: "asbru-cm"
    state: present

- name: Remove the Ásbrú install script
  file: 
    path: /tmp/asbru-cm-release_deb.sh 
    state: absent